global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      # 这里指向一个不存在的地址作为占位，或者你可以填真实的 Webhook URL
      - url: 'http://127.0.0.1:5001/'
